# Deploy to Azure Kubernetes Service

# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '47ef203c-db2c-4062-aa83-df48cee9b5f8'
  imageRepository: 'shoppingapi'
  containerRegistry: 'swnzenacr.azurecr.io'
  dockerfilePath: 'swnzen/Shopping.API/Dockerfile'
  tag: '$(Build.BuildId)'  
  deploymentFile: 'shoppingapi.yaml'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)/swnzen
        tags: |
          $(tag)        

- stage: Deploy
  displayName: Deploy to AKS stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: $(vmImageName)
    environment: 'mehmetozkayaswnzen-8332.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'myAKSCluster-default'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: '$(Build.SourcesDirectory)/swnzen/azure/aks/$(deploymentFile)'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'              
              azureSubscriptionEndpointForSecrets: 'Free Trial(7fc43c1a-9019-44b5-bb83-e4bcae6a9155)'
              azureContainerRegistry: $(containerRegistry)
              secretName: 'acr-secret'